# The URL the site will be built for
base_url = "https://jan.systems"

title = "Jan Sydänviita (né Tuomi)"
description = "Minimalist, digital gardener, senior software engineer."
default_language = "en"
generate_feeds = true
feed_filenames = ["atom.xml"]
author = "Jan Sydänviita (né Tuomi)"
generate_sitemap = true
generate_robots_txt = true
compile_sass = false
build_search_index = false

taxonomies = [{ name = "kind", feed = true }]

[markdown]
external_links_target_blank = true
bottom_footnotes = true
lazy_async_image = false
insert_anchor_links = "heading"

[markdown.highlighting]
# A valid theme is required, but not actually used. `style.css` overrides the highlighting classes (z-*).
# Causes static/giallo.css to be generated.
theme = "github-dark"
style = "class"
error_on_missing_language = true

[extra]
# Put all your custom variables here
